### ISSUE TITLE
fixed after gmod update 02.07.2019

### ISSUE THREAD

**Issue by CoolGoga** [DuckyC/gmsv_query#7]
> require("query")...
Segmentation fault
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Tue Jul  2 20:42:18 MSK 2019: Server restart in 10 seconds

**Comment by Heyter** [comment]
Linux: recompile module.

**Comment by MVoloshin** [comment]
Is linux still supported?

**Comment by CoolGoga** [comment]
Ребята, не стоит вскрывать эту тему. Вы молодые, шутливые, вам все легко. Это не то. Это не Чикатило и даже не архивы спецслужб. Сюда лучше не лезть. Серьезно, любой из вас будет жалеть. Лучше закройте тему и забудьте, что тут писалось. Я вполне понимаю, что данным сообщением вызову дополнительный интерес, но хочу сразу предостеречь пытливых - стоп. Остальные просто не найдут.
